#!/usr/bin/env zsh
# Completions and Functions
fpath=(~/.zsh/completions ~/.zsh/scripts ~/.zsh-completions/src /usr/local/share/zsh-completions $fpath)
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle :compinstall filename '/Users/yulian/.zshrc'

autoload -Uz compinit promptinit zkbd $fpath[2]/*(.:t)
compinit
promptinit
autoload -U +X bashcompinit && bashcompinit

# History and Options
HISTFILE=~/.zhist
HISTSIZE=20000
SAVEHIST=10000
setopt appendhistory autocd extendedglob incappendhistory histexpiredupsfirst histnostore histreduceblanks
setopt notify completealiases prompt_subst nullglob rematchpcre
bindkey -e
export MICRO_TRUECOLOR=true
export EDITOR="micro"
umask 022

# Terminal Colors and PS1
export TERM=xterm-256color
export PS1="$(print '%F{214}[%F{81}%m%F{14}|%F{214}%~%F{214}]%F{39} \n>>%{$reset_color%} ')"
export CLICOLOR=1
export LSOPTIONS="--color=always"
export LC_ALL="en_US.UTF-8"

# Nix Vars
source ~/.nix-profile/etc/profile.d/nix.sh
source ~/.nix-profile/etc/profile.d/nix-daemon.sh
source ~/.nix-profile/etc/profile.d/hm-session-vars.sh

# Keybinds
source ~/.zsh/keybinds.zsh

# Aliases
source ~/.zsh/aliases/docker.zsh
source ~/.zsh/aliases/exa.zsh
source ~/.zsh/aliases/files.zsh
source ~/.zsh/aliases/git.zsh
source ~/.zsh/aliases/kubernetes.zsh
source ~/.zsh/aliases/linux.zsh
source ~/.zsh/aliases/macos.zsh
source ~/.zsh/aliases/noglob.zsh
source ~/.zsh/aliases/other.zsh
source ~/.zsh/aliases/windows.zsh

# App Settings
source ~/.zsh/apps/copilot-cli.zsh
source ~/.zsh/apps/easy_colors.zsh
source ~/.zsh/apps/fzf.zsh
source ~/.zsh/apps/nodejs.zsh
source ~/.zsh/apps/zicd.zsh
source ~/.zsh/apps/wasmer.zsh

# Theme
source ~/.p10k.zsh
source ~/.powerlevel10k/powerlevel10k.zsh-theme
