path=(
  $FLYCTL_INSTALL/bin
  $HOME/.bin
  $HOME/.cargo/bin
  $HOME/.local/bin
  $HOME/.go/bin
  $HOME/.poetry/bin
  $HOME/.pyenv/bin
  $HOME/.npm-packages/bin
  $path
)

export CLICOLORS="1"
export EDITOR="micro"
export FLYCTL_INSTALL="{{home_path}}/.fly"
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"
export FZF_CTRL_T_COMMAND="fd --type f --hidden --follow --exclude .git"
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"
export GLAMOUR_STYLE="dark"
export GOPATH="{{home_path}}/.go"
export GOPROXY="https://proxy.golang.org,direct"
export LC_ALL="en_US.UTF-8"
export LSOPTIONS="--color=always"
export MICRO_TRUECOLOR="true"
export NVM_DIR="{{home_path}}/.nvm"
export TERM="xterm-256color"
export USING_NIX="true"
export WORKSPACE_ROOT="{{home_path}}/workspace/code"
export HOMEBREW_NO_ENV_HINTS="1"

if [[ $HOSTNAME == "lx1e"* ]]; then
    export USE_GKE_GCLOUD_AUTH_PLUGIN="true";
    export WASMER_DIR="{{home_path}}/.wasmer";
fi
