[symlinks]
"files/atuin.toml" = "/home/yulian/.config/atuin/config.toml"
"files/foot.ini" = "/home/yulian/.config/foot/foot.ini"
"files/gh/config.yml" = "/home/yulian/.config/gh/config.yml"
"files/gh/hosts.yml" = "/home/yulian/.config/gh/hosts.yml"
"files/git/config" = "/home/yulian/.config/git/config"
"files/git/ignore" = "/home/yulian/.config/git/ignore"
"files/starship.toml" = "/home/yulian/.config/starship.toml"
"files/zshrc" = "/home/yulian/.zshrc"

[templates]
