packages = [
  "1password",
  "atuin",
  "foot",
  "gh",
  "git",
  "ssh",
  "starship",
  "zsh",
]

[variables]
user_email = "yulian@unity3d.com"
signing_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFNxxHTLK5zifEU0zVVPVqfxZYadRj79QPqEjWbXHKD4"
home_path = "/home/yulian"
hostname = "yulian-dp7680"
ssh_1password_vault = "Work"
ssh_key = "work-dp7680"
